blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/kionsoftware/kion-cli/discussions/new?category=q-a
    about: Something not working the way you expect? Open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/kionsoftware/kion-cli/discussions/new?category=ideas
    about: Have a need or great idea? Make a suggestion using our discussion forums.
