# Copyright (c) Kion Software

# REPLACE_AUTOGENERATED
class REPLACE_CLASSNAME < Formula
  desc "Kion on the command-line!"
  homepage "https://github.com/kionsoftware/kion-cli"
  version "REPLACE_VERSION"
  license "MIT"

  url "REPLACE_ARCHIVE_URL"
  sha256 "REPLACE_CHECKSUM"
  head "https://github.com/kionsoftware/kion-cli"

  depends_on "go" => :build

  def install
    zsh_completion.install "_kion"
    ENV["GOPATH"] = buildpath
    bin_path = buildpath/"src/github.com/kionsoftware/kion-cli"
    bin_path.install Dir["*"]
    cd bin_path do
      system "go", "build", "-o", "#{bin}/kion", "."
    end
  end

  test do
    system "#{bin}/kion", "--version"
  end
end
