#!/bin/sh
#
# Kion CLI pre-commit hook.
#
# Run various checks and cleanups before committing.
#
# Author(s): Cody Buell
#
# Requisite:
#
# Usage: Intended to be placed in [proj dir]/.git/hooks and called via git

export BOLD="$(tput bold)"
export UNDER="$(tput smul)"
export NOUNDER="$(tput rmul)"
export DIM="$(tput dim)"

export BLACK="$(tput setaf 0)"
export RED="$(tput setaf 1)"
export GREEN="$(tput setaf 2)"
export YELLOW="$(tput setaf 3)"
export BLUE="$(tput setaf 4)"
export MAGENTA="$(tput setaf 5)"
export CYAN="$(tput setaf 6)"
export WHITE="$(tput setaf 7)"

export NORM="$(tput sgr0)"

# determine md5 binary name
if which md5 &> /dev/null; then
  MD5='md5'
  MD5Q='md5 -q'
else
  MD5='md5sum'
  MD5Q='md5sum'
fi

# check for a newer version of the pre-commit hook
MD5HOOK=$(${MD5Q} ".git/hooks/pre-commit" | awk '{print $1}')
MD5REPO=$(${MD5Q} "tools/pre-commit" | awk '{print $1}')
if [[ ${MD5HOOK} != ${MD5REPO} ]]; then
  make init
  echo
  echo "${BOLD}${YELLOW}The pre-commit git hook was out of date and has been updated.${NORM}"
  echo "${BOLD}${YELLOW}Please re-run your last git commit.${NORM}"
  exit 1
fi

# lint
make lint
if [[ $? != 0 ]]; then
  echo
  echo "${BOLD}${RED}The above linting errors were found, please correct before committing.${NORM}"
  exit 1
fi

# test
make test
if [[ $? != 0 ]]; then
  echo
  echo "${BOLD}${RED}The above testing errors were found, please correct before committing.${NORM}"
  exit 1
fi

echo
